using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using InternManagement.Data;
using InternManagement.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

var builder = WebApplication.CreateBuilder(args);
builder.Configuration.AddJsonFile("appsettings.Database.json", optional: true, reloadOnChange: true);
builder.Services.AddOpenApi();

var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
if (string.IsNullOrWhiteSpace(connectionString))
    throw new InvalidOperationException("Thiếu ConnectionStrings:DefaultConnection. Hãy tạo appsettings.Database.json theo file mẫu.");

var jwtKey = builder.Configuration["Jwt:Key"];
if (string.IsNullOrWhiteSpace(jwtKey) || jwtKey.StartsWith("REPLACE_", StringComparison.Ordinal)
    || Encoding.UTF8.GetByteCount(jwtKey) < 32)
    throw new InvalidOperationException("Jwt:Key phải có ít nhất 32 byte. Hãy cấu hình trong appsettings.Database.json.");
var jwtIssuer = builder.Configuration["Jwt:Issuer"] ?? "InternManagement";
var jwtAudience = builder.Configuration["Jwt:Audience"] ?? "InternManagementFrontend";
builder.Services.AddDbContext<AppDbContext>(options => options.UseNpgsql(connectionString));
builder.Services.AddScoped<IPasswordHasher<AppUser>, PasswordHasher<AppUser>>();
builder.Services.AddCors(options => options.AddDefaultPolicy(policy => policy
    .WithOrigins(
        "http://127.0.0.1:5148",
        "http://localhost:5148")
    .AllowAnyHeader()
    .AllowAnyMethod()));
builder.Services.AddAuthentication("Bearer").AddJwtBearer("Bearer", options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidIssuer = jwtIssuer,
        ValidateAudience = true,
        ValidAudience = jwtAudience,
        ValidateIssuerSigningKey = true,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey)),
        ValidateLifetime = true,
        ClockSkew = TimeSpan.FromSeconds(30)
    };
});
builder.Services.AddAuthorization();

var app = builder.Build();
if (app.Environment.IsDevelopment()) app.MapOpenApi();
app.UseCors();
app.UseAuthentication();
app.UseAuthorization();

// Create the initial schema and add the local development administrator.
await using (var scope = app.Services.CreateAsyncScope())
{
    var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    await db.Database.EnsureCreatedAsync();

    // EnsureCreated does not add tables when the database already contains unrelated tables.
    await db.Database.ExecuteSqlRawAsync("""
        CREATE TABLE IF NOT EXISTS "Users" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "FullName" character varying(150) NOT NULL,
            "Email" character varying(256) NOT NULL,
            "UserName" character varying(256),
            "PasswordHash" character varying(500) NOT NULL,
            "Role" character varying(20) NOT NULL
        )
        """);

    // Upgrade databases created before the UserName property was added.
    await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Users\" ADD COLUMN IF NOT EXISTS \"UserName\" character varying(256)");
    await db.Database.ExecuteSqlRawAsync("UPDATE \"Users\" SET \"UserName\" = \"Email\" WHERE \"UserName\" IS NULL OR \"UserName\" = ''");
    await db.Database.ExecuteSqlRawAsync("ALTER TABLE \"Users\" ALTER COLUMN \"UserName\" SET NOT NULL");
    await db.Database.ExecuteSqlRawAsync("CREATE UNIQUE INDEX IF NOT EXISTS \"IX_Users_Email\" ON \"Users\" (\"Email\")");
    await db.Database.ExecuteSqlRawAsync("CREATE UNIQUE INDEX IF NOT EXISTS \"IX_Users_UserName\" ON \"Users\" (\"UserName\")");

    if (!await db.Users.AnyAsync(user => user.Email == "admin@gmail.com"))
    {
        var passwordHasher = new PasswordHasher<AppUser>();
        var admin = new AppUser
        {
            FullName = "Administrator",
            Email = "admin@gmail.com",
            UserName = "admin@gmail.com",
            PasswordHash = "",
            Role = "ADMIN"
        };
        admin.PasswordHash = passwordHasher.HashPassword(admin, "Admin@123");
        db.Users.Add(admin);
        await db.SaveChangesAsync();
    }
}

app.MapPost("/api/auth/login", async (LoginRequest request, AppDbContext db,
    IPasswordHasher<AppUser> passwordHasher, IConfiguration config) =>
{
    var username = request.Username?.Trim();
    if (string.IsNullOrWhiteSpace(username) || string.IsNullOrEmpty(request.Password))
        return (IResult)Results.BadRequest(new { message = "Vui lòng nhập email và mật khẩu." });

    var user = await db.Users.SingleOrDefaultAsync(item => item.Email == username || item.UserName == username);
    if (user is null || passwordHasher.VerifyHashedPassword(user, user.PasswordHash, request.Password)
        == PasswordVerificationResult.Failed)
        return (IResult)Results.Json(new { message = "Email hoặc mật khẩu không chính xác." }, statusCode: StatusCodes.Status401Unauthorized);

    var issuer = config["Jwt:Issuer"] ?? "InternManagement";
    var audience = config["Jwt:Audience"] ?? "InternManagementFrontend";
    var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(config["Jwt:Key"]!));
    var claims = new[]
    {
        new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
        new Claim(ClaimTypes.Name, user.Email),
        new Claim(ClaimTypes.Role, user.Role)
    };
    var token = new JwtSecurityToken(issuer, audience, claims,
        expires: DateTime.UtcNow.AddHours(8),
        signingCredentials: new SigningCredentials(key, SecurityAlgorithms.HmacSha256));

    return (IResult)Results.Ok(new
    {
        token = new JwtSecurityTokenHandler().WriteToken(token),
        user = new { id = user.Id, fullName = user.FullName, email = user.Email, role = user.Role }
    });
});

var adminUsers = app.MapGroup("/api/users").RequireAuthorization(policy => policy.RequireRole("ADMIN"));
adminUsers.MapGet("", async (AppDbContext db) => Results.Ok(await db.Users
    .OrderBy(user => user.FullName)
    .Select(user => new UserResponse(user.Id, user.FullName, user.Email, user.Role))
    .ToListAsync()));

adminUsers.MapGet("/{id:int}", async (int id, AppDbContext db) =>
{
    var user = await db.Users.FindAsync(id);
    return user is null
        ? Results.NotFound(new { message = "Không tìm thấy tài khoản." })
        : Results.Ok(new UserResponse(user.Id, user.FullName, user.Email, user.Role));
});

adminUsers.MapPost("", async (CreateUserRequest request, AppDbContext db,
    IPasswordHasher<AppUser> passwordHasher) =>
{
    var fullName = request.FullName?.Trim();
    var email = request.Email?.Trim();
    var role = request.Role?.Trim().ToUpperInvariant();
    if (string.IsNullOrWhiteSpace(fullName) || string.IsNullOrWhiteSpace(email)
        || string.IsNullOrWhiteSpace(request.Password) || request.Password.Length < 8
        || role is not ("HR" or "MENTOR" or "INTERN"))
        return (IResult)Results.BadRequest(new { message = "Thông tin không hợp lệ. Mật khẩu tối thiểu 8 ký tự; vai trò hợp lệ: HR, MENTOR, INTERN." });
    if (await db.Users.AnyAsync(user => user.Email == email))
        return (IResult)Results.Conflict(new { message = "Email đã được sử dụng." });

    var user = new AppUser
    {
        FullName = fullName,
        Email = email,
        UserName = email,
        PasswordHash = "",
        Role = role
    };
    user.PasswordHash = passwordHasher.HashPassword(user, request.Password);
    db.Users.Add(user);
    await db.SaveChangesAsync();
    return (IResult)Results.Created($"/api/users/{user.Id}", new
    {
        message = "Tạo tài khoản thành công.",
        user = new UserResponse(user.Id, user.FullName, user.Email, user.Role)
    });
});

adminUsers.MapPut("/{id:int}", async (int id, UpdateUserRequest request, AppDbContext db,
    IPasswordHasher<AppUser> passwordHasher) =>
{
    var user = await db.Users.FindAsync(id);
    if (user is null) return (IResult)Results.NotFound(new { message = "Không tìm thấy tài khoản." });

    var fullName = request.FullName?.Trim();
    var email = request.Email?.Trim();
    var role = request.Role?.Trim().ToUpperInvariant();
    if (string.IsNullOrWhiteSpace(fullName) || string.IsNullOrWhiteSpace(email)
        || role is not ("ADMIN" or "HR" or "MENTOR" or "INTERN")
        || (!string.IsNullOrEmpty(request.Password) && request.Password.Length < 8))
        return (IResult)Results.BadRequest(new { message = "Thông tin không hợp lệ. Mật khẩu mới phải có ít nhất 8 ký tự; vai trò hợp lệ: ADMIN, HR, MENTOR, INTERN." });

    if (await db.Users.AnyAsync(item => item.Id != id && item.Email == email))
        return (IResult)Results.Conflict(new { message = "Email đã được sử dụng." });

    user.FullName = fullName;
    user.Email = email;
    user.UserName = email;
    user.Role = role;
    if (!string.IsNullOrEmpty(request.Password))
        user.PasswordHash = passwordHasher.HashPassword(user, request.Password);

    await db.SaveChangesAsync();
    return (IResult)Results.Ok(new
    {
        message = "Cập nhật tài khoản thành công.",
        user = new UserResponse(user.Id, user.FullName, user.Email, user.Role)
    });
});

adminUsers.MapDelete("/{id:int}", async (int id, AppDbContext db, ClaimsPrincipal principal) =>
{
    var currentId = principal.FindFirstValue(ClaimTypes.NameIdentifier);
    if (currentId == id.ToString())
        return (IResult)Results.BadRequest(new { message = "Không thể xóa tài khoản đang đăng nhập." });
    var user = await db.Users.FindAsync(id);
    if (user is null) return (IResult)Results.NotFound(new { message = "Không tìm thấy tài khoản." });
    db.Users.Remove(user);
    await db.SaveChangesAsync();
    return (IResult)Results.Ok(new { message = "Đã xóa tài khoản." });
});

app.Run();

record LoginRequest(string? Username, string? Password);
record CreateUserRequest(string? FullName, string? Email, string? Password, string? Role);
record UpdateUserRequest(string? FullName, string? Email, string? Password, string? Role);
record UserResponse(int Id, string FullName, string Email, string Role);
