(() => {
  const API = `${window.APP_CONFIG?.apiBaseUrl || "http://localhost:5024/api"}/intern-portal`;
  const token = localStorage.getItem("token");
  const $ = (s, root = document) => root.querySelector(s);
  const content = $("#internContent"), dialog = $("#internDialog");
  let page = "dashboard", me = null, toastTimer;
  const labels = { NotStarted:"Chưa bắt đầu", InProgress:"Đang thực hiện", PendingReview:"Chờ Mentor đánh giá", Completed:"Hoàn thành", Submitted:"Đã nộp", RevisionRequested:"Yêu cầu chỉnh sửa", Approved:"Đã duyệt", Rejected:"Từ chối", Scheduled:"Đã lên lịch", Cancelled:"Đã hủy", Praise:"Khen ngợi", Suggestion:"Gợi ý", Warning:"Cảnh báo", Improvement:"Cần cải thiện" };
  const esc = v => String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const fmt = v => v ? new Date(v).toLocaleString("vi-VN", { dateStyle:"medium", timeStyle:"short" }) : "—";
  async function api(path, options = {}) {
    let response;
    try { response = await fetch(API + path, { ...options, headers:{ "Content-Type":"application/json", Authorization:token ? `Bearer ${token}` : "", ...options.headers } }); }
    catch { throw new Error("Không kết nối được Backend. Hãy kiểm tra backend và địa chỉ API."); }
    const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(data.message || `Lỗi HTTP ${response.status}`);
    return data;
  }
  const toast = msg => { const el=$("#internToast"); el.textContent=msg; el.classList.add("show"); clearTimeout(toastTimer); toastTimer=setTimeout(()=>el.classList.remove("show"),3000); };
  const box = (title, body, action="") => `<section class="panel"><div class="panel-head"><h2>${title}</h2>${action}</div><div class="panel-body">${body || '<div class="empty-state">Chưa có dữ liệu.</div>'}</div></section>`;
  const heading = (title, sub, action="") => `<div class="page-heading"><div><p class="eyebrow">INTERN WORKSPACE</p><h1>${title}</h1><p>${sub}</p></div>${action}</div>`;
  const badge = s => `<span class="badge ${s==='Completed'||s==='Approved'?'green':s==='Rejected'?'red':'amber'}">${esc(labels[s]||s||'—')}</span>`;
  function table(headers, rows) { return rows.length ? `<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>` : '<div class="empty-state">Chưa có dữ liệu.</div>'; }
  async function load(pageName=page) {
    page=pageName; document.querySelectorAll("#internNav [data-page]").forEach(b=>b.classList.toggle("active",b.dataset.page===page));
    $("#internSection").textContent=({dashboard:"Dashboard",tasks:"Nhiệm vụ",reports:"Báo cáo",evaluations:"Đánh giá",schedules:"Lịch mentoring",feedback:"Feedback",notifications:"Thông báo",profile:"Hồ sơ cá nhân"})[page];
    $("#internSidebar").classList.remove("open"); content.innerHTML='<div class="loading-state">Đang tải...</div>';
    try { await renderers[page](); } catch(e) { content.innerHTML=`<div class="error-state">${esc(e.message)}<br><button class="button" data-action="retry">Thử lại</button></div>`; }
  }
  async function fetchMe(){ me=await api('/me'); $("#internName").textContent=me.FullName||'Intern'; $("#internEmail").textContent=me.Email||''; $("#internAvatar").textContent=(me.FullName||'IN').split(/\s+/).slice(-2).map(x=>x[0]).join('').toUpperCase(); }
  const renderers = {
    dashboard: async()=>{ await fetchMe(); const [tasks,reports,notes]=await Promise.all([api('/tasks'),api('/reports'),api('/notifications')]); const unread=notes.filter(n=>!n.ReadAt).length; $("#internUnread").hidden=!unread; $("#internUnread").textContent=unread||'';
      const open=tasks.filter(t=>t.Status!=='Completed').length, pending=tasks.filter(t=>t.Status==='PendingReview').length;
      content.innerHTML=heading(`Xin chào, ${esc(me.FullName)}`,`${esc(me.MentorName||'Chưa có Mentor được phân công')} · ${esc(me.InternshipPosition||'Thực tập sinh')}`)+`<div class="stats-grid"><article class="stat-card"><div class="stat-label">Nhiệm vụ</div><div class="stat-value">${tasks.length}</div><div class="stat-note">${open} nhiệm vụ đang mở</div></article><article class="stat-card"><div class="stat-label">Chờ đánh giá</div><div class="stat-value">${pending}</div><div class="stat-note">Nhiệm vụ đã gửi Mentor</div></article><article class="stat-card"><div class="stat-label">Báo cáo</div><div class="stat-value">${reports.length}</div><div class="stat-note">Báo cáo đã nộp</div></article><article class="stat-card"><div class="stat-label">Tiến độ hồ sơ</div><div class="stat-value">${Number(me.Progress)||0}%</div><div class="stat-note">${esc(me.Status||'')}</div></article></div><div class="two-col">${box('Thông tin thực tập',`<p><b>Trường:</b> ${esc(me.School)}</p><p><b>Chuyên ngành:</b> ${esc(me.Major)}</p><p><b>Thời gian:</b> ${fmt(me.StartDate)} – ${fmt(me.EndDate)}</p><p><b>Mentor:</b> ${esc(me.MentorName||'Chưa phân công')}</p>`)}${box('Nhiệm vụ gần đây',table(['Nhiệm vụ','Hạn','Trạng thái'],tasks.slice(0,5).map(t=>`<tr><td>${esc(t.Title)}</td><td>${fmt(t.Deadline)}</td><td>${badge(t.Status)}</td></tr>`)))}</div>`; },
    tasks: async()=>{ const rows=await api('/tasks'); content.innerHTML=heading('Nhiệm vụ của tôi','Theo dõi và cập nhật trạng thái nhiệm vụ do Mentor giao.')+box('Danh sách nhiệm vụ',table(['Nhiệm vụ','Mô tả','Hạn','Ưu tiên','Trạng thái','Thao tác'],rows.map(t=>`<tr><td>${esc(t.Title)}</td><td>${esc(t.Description)}</td><td>${fmt(t.Deadline)}</td><td>${esc(t.Priority)}</td><td>${badge(t.Status)}</td><td>${t.Status==='Completed'?'—':`<button class="button" data-action="task-start" data-id="${t.Id}">Bắt đầu</button> <button class="button primary" data-action="task-submit" data-id="${t.Id}">Gửi đánh giá</button>`}</td></tr>`))); },
    reports: async()=>{ const rows=await api('/reports'); content.innerHTML=heading('Báo cáo thực tập','Nộp báo cáo cho Mentor và xem lại nhận xét.','<button class="button primary" data-action="new-report">+ Nộp báo cáo</button>')+box('Báo cáo của tôi',table(['Tiêu đề','Nội dung','Ngày nộp','Trạng thái'],rows.map(r=>`<tr><td>${esc(r.Title)}</td><td>${esc(r.Content)}</td><td>${fmt(r.SubmittedAt)}</td><td>${badge(r.Status)}</td></tr>`))); },
    evaluations: async()=>{ const rows=await api('/evaluations'); content.innerHTML=heading('Đánh giá','Kết quả đánh giá đã được Mentor gửi.')+box('Lịch sử đánh giá',rows.length?rows.map(e=>`<article class="list-row"><div class="list-main"><strong>${esc(e.MentorName)} · ${fmt(e.UpdatedAt)}</strong><p>${esc(e.Comments)}</p><p>${esc(e.Recommendation)}</p><small>${(e.scores||[]).map(s=>`${esc(s.Criterion)}: ${s.Score}/10`).join(' · ')}</small></div></article>`).join(''):'<div class="empty-state">Chưa có đánh giá được công bố.</div>'); },
    schedules: async()=>{ const rows=await api('/schedules'); content.innerHTML=heading('Lịch mentoring','Các buổi làm việc sắp tới với Mentor.')+box('Lịch của tôi',table(['Buổi làm việc','Bắt đầu','Kết thúc','Địa điểm','Mentor','Ghi chú'],rows.map(s=>`<tr><td>${esc(s.Title)}<br>${esc(s.Content)}</td><td>${fmt(s.StartsAt)}</td><td>${fmt(s.EndsAt)}</td><td>${esc(s.Location)}</td><td>${esc(s.MentorName)}</td><td>${esc(s.Notes)}</td></tr>`))); },
    feedback: async()=>{ const rows=await api('/feedback'); content.innerHTML=heading('Feedback','Nhận xét và hướng dẫn từ Mentor.')+box('Phản hồi',rows.length?rows.map(f=>`<article class="list-row"><div class="list-main"><strong>${esc(labels[f.Type]||f.Type)} · ${esc(f.MentorName)} ${badge(f.Severity)}</strong><p>${esc(f.Content)}</p><small>${fmt(f.CreatedAt)}</small></div></article>`).join(''):'<div class="empty-state">Chưa có feedback.</div>'); },
    notifications: async()=>{ const rows=await api('/notifications'); const unread=rows.filter(n=>!n.ReadAt).length; $("#internUnread").hidden=!unread; $("#internUnread").textContent=unread||''; content.innerHTML=heading('Thông báo','Cập nhật nhiệm vụ, báo cáo và lịch mentoring.',unread?'<button class="button" data-action="read-all">Đánh dấu tất cả đã đọc</button>':'')+box('Hộp thư',rows.length?rows.map(n=>`<article class="list-row"><div class="list-main"><strong>${esc(n.Title)} ${n.ReadAt?'':'• Mới'}</strong><p>${esc(n.Message)}</p><small>${fmt(n.CreatedAt)}</small></div>${n.ReadAt?'':`<button class="button" data-action="read-note" data-id="${n.Id}">Đã đọc</button>`}</article>`).join(''):'<div class="empty-state">Chưa có thông báo.</div>'); },
    profile: async()=>{ await fetchMe(); content.innerHTML=heading('Hồ sơ cá nhân','Thông tin hồ sơ thực tập của bạn.')+box('Thông tin',`<div class="profile-grid"><p><b>Họ tên</b><br>${esc(me.FullName)}</p><p><b>MSSV</b><br>${esc(me.Mssv)}</p><p><b>Email</b><br>${esc(me.Email)}</p><p><b>Điện thoại</b><br>${esc(me.Phone)}</p><p><b>Trường</b><br>${esc(me.School)}</p><p><b>Chuyên ngành</b><br>${esc(me.Major)}</p><p><b>Vị trí</b><br>${esc(me.InternshipPosition)}</p><p><b>Phòng ban</b><br>${esc(me.Department)}</p><p><b>Mentor</b><br>${esc(me.MentorName||'Chưa phân công')}</p><p><b>Tiến độ</b><br>${Number(me.Progress)||0}%</p></div>`); }
  };
  function showReportForm(){ $("#internDialogBody").innerHTML=`<h2>Nộp báo cáo</h2><form id="reportForm" class="form-grid"><label>Tiêu đề<input name="title" maxlength="200" required></label><label>Nội dung<textarea name="content" rows="8" maxlength="50000" required></textarea></label><label>Liên kết tệp (nếu có)<input name="attachmentUrl" type="url" maxlength="1000"></label><button class="button primary">Gửi báo cáo</button></form>`; dialog.showModal(); }
  document.addEventListener('click',async e=>{ const nav=e.target.closest('[data-page]'); if(nav){load(nav.dataset.page);return;} const goto=e.target.closest('[data-goto]');if(goto){load(goto.dataset.goto);return;}const b=e.target.closest('[data-action]');if(!b)return;try{const id=b.dataset.id;switch(b.dataset.action){case'retry':load();break;case'new-report':showReportForm();break;case'task-start':await api(`/tasks/${id}/status`,{method:'PUT',body:JSON.stringify({status:'InProgress'})});toast('Đã cập nhật nhiệm vụ.');load();break;case'task-submit':await api(`/tasks/${id}/status`,{method:'PUT',body:JSON.stringify({status:'PendingReview'})});toast('Đã gửi nhiệm vụ cho Mentor đánh giá.');load();break;case'read-note':await api(`/notifications/${id}/read`,{method:'PUT'});load();break;case'read-all':for(const n of await api('/notifications'))if(!n.ReadAt)await api(`/notifications/${n.Id}/read`,{method:'PUT'});load();break;}}catch(err){toast(err.message);}});
  document.addEventListener('submit',async e=>{if(e.target.id!=='reportForm')return;e.preventDefault();const f=new FormData(e.target);try{await api('/reports',{method:'POST',body:JSON.stringify({title:f.get('title'),content:f.get('content'),attachmentUrl:f.get('attachmentUrl')||null})});dialog.close();toast('Đã nộp báo cáo.');load('reports');}catch(err){toast(err.message);}});
  $("#internMobileMenu")?.addEventListener('click',()=>$("#internSidebar").classList.toggle('open'));
  $("#internLogout")?.addEventListener('click',()=>{localStorage.removeItem('token');localStorage.removeItem('role');localStorage.removeItem('user');location.href='../index.html';});
  load('dashboard');
})();
